-- Write your sql migration here!
CREATE TABLE owner (
id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY UNIQUE,
owner_id BIGINT NOT NULL,
owner_type SMALLINT NOT NULL,
created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS account(
id BIGINT PRIMARY KEY generated always AS IDENTITY UNIQUE,
account_number VARCHAR (20) CHECK (LENGTH(account_number) BETWEEN 12 AND 20) NOT NULL UNIQUE,
account_owner BIGINT,
account_type VARCHAR (32),
currency VARCHAR (3) NOT NULL,
status VARCHAR (16) NOT NULL,
created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
closed_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
version BIGINT NOT NULL,

CONSTRAINT fk_account_owner FOREIGN KEY (account_owner) REFERENCES owner (id)
);

CREATE INDEX owner_idx ON account (account_owner);