ALTER TABLE request
ADD COLUMN context VARCHAR(255);

ALTER TABLE request
ADD COLUMN scheduled_at TIMESTAMP;

ALTER TABLE request
ADD COLUMN rollback_status VARCHAR(64) DEFAULT 'NOT_STARTED';

ALTER TABLE request
ALTER COLUMN version TYPE BIGINT;
